# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_secrets_management:
    name: do secrety things
    # This job runs on self hosted Linux machine, with public label
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ci-test
          clean: true
#      - uses: actions/checkout@v2
#        with:
#          repository: armbian/ci-testing-tools
#          path: ci-testing-tools
#          ref: secrets
      - name: Do some tests
        shell: bash {0}         
        run: |  
         #source ci-testing-tools/jenkins_ci.sh
         cd ci-test
         TEST_HOST=ec2-54-211-123-105.compute-1.amazonaws.com
         TEST_USER=github
         SSH_KEYFILE="secrets/test_ssh_key.cpt"
         uuidgen > testfile
         set -x
         rsync -auv -e "ssh -i <(ccat $PWD/${SSH_KEYFILE} -K ${{secrets.keyword}})" testfile ${TEST_USER}@${TEST_HOST}:
